name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check that index.html exists
        run: |
          if [ ! -f index.html ]; then echo 'index.html missing' && exit 1; fi
      - name: Validate internal links (basic)
        run: |
          # find internal links and curl them to ensure 200
          grep -Eo "href=\"/[^\"]+\"" -R | sed -E 's/href=\"([^\"]+)\"/\1/' | sort -u > /tmp/links.txt || true
          echo 'Found links:' && cat /tmp/links.txt
          set -e
          while read -r l; do
            url="http://localhost:1313$l"
            # serve site using a simple python server in background
          done

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
